services:
  app:
    image: best-insurance/api
    ports:
      - 8080:8080
    env_file: ../.env
    environment:
      -  POSTGRES_DB
    networks:
      - spring-postgres
  db:
    image: postgres
    restart: always
    env_file: ../.env
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    expose:
      - 5432
    networks:
      - spring-postgres

networks:
  spring-postgres: