services:
  backend:
    build: bestInsuranceApi #path to docker file
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=bestinsurance
    networks:
      - spring-postgres
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=bestinsurance
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
volumes:
  db-data:
secrets:
  db-password:
    file: ../db/password.txt
networks:
  spring-postgres: