services:
  app:
    build: .
    image: best_insurance/api:latest
    container_name: app
    depends_on:
      db:
        condition: service_started
    ports:
      - '8080:8080'
    env_file: .env

  db:
    image: 'postgres:14.5-alpine'
    container_name: db
    env_file: .env
    ports:
      - '54320:5432'
